v11 r4.4
Issue
Error: Voucher totals do not match.

Cause of Error
This error occurs when voucher entry has TCS amount with decimals.

Note: The Round off ledger does not appear (in xml / debug mode)

Status
This bug has been rectified now.